# fly.toml app configuration file generated for joayo-api on 2026-07-09T15:02:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'joayo-api'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  DB_PATH = '/data/places.db'

[[mounts]]
  source = 'joayo_data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpus = 1
  memory_mb = 512
